[package]
name = "waveless_sql"
description = "Waveless' MySQL and PostgreSQL support."
version = "0.0.1"
homepage = "https://github.com/nv0skar/waveless_sql"
repository = "https://github.com/nv0skar/waveless_sql"
edition = "2024"

[dependencies]
rustyrosetta = { git = "https://github.com/nv0skar/RustyRosetta.git", tag = "rustyrosetta_0.0.4", features = [
    "all",
] }
boxed_any = { git = "https://github.com/nv0skar/BoxedAny.git" }
boxed_any_derive = { git = "https://github.com/nv0skar/BoxedAny.git" }

waveless_commons = { git = "https://github.com/nv0skar/Waveless.git" }

serde = { version = "1.0.229", features = ["derive", "rc"] }
serde_json = "1.0"
serde_with = { version = "3.21", features = ["chrono"] }

http = "1.4.2"

bytes = "1.12"

sqlx = { version = "0.9.0", features = [
    "runtime-tokio",
    "tls-rustls",
    "json",
] }
sea-orm = { version = "2.0.3", features = [ "runtime-tokio-rustls", "schema-sync" ] }
sea-schema = { git = "https://github.com/nv0skar/sea-schema-mysql.git", features = [
    "runtime-tokio",
    "runtime-tokio-rustls",
] }

chrono = { version = "0.4.45", default-features = false, features = [
    "clock",
    "serde",
] }

typetag = "0.2"
async-trait = "0.1"
dyn-clone = "1.0.20"

struct-patch = "0.14"

smallvec = { version = "1.15", features = ["serde", "write", "const_new"] }
arrayvec = { version = "0.7", features = ["serde"] }
smallbox = "0.8"
dashmap = "6.2"
rclite = "0.4"
compact_str = { version = "0.10", features = ["serde"] }

rand = "0.10"

crc32fast = "1.5"

regex = "1.13"

tracing = "0.1"

itertools = "0.15"

getset = "0.1"
eyre = "0.6"
color-eyre = "0.6"
derive_builder = "0.20"
derive_more = { version = "2.1", features = ["constructor", "display"] }

[features]
default = ["all"]

all = ["mysql", "postgres"]

mysql = ["sqlx/mysql", "sea-orm/sqlx-mysql", "sea-schema/sqlx-mysql"]
postgres = ["sqlx/postgres", "sea-orm/sqlx-postgres", "sea-schema/sqlx-postgres"]

[workspace.lints.rust]
unexpected_cfgs = "deny"

[profile.dev.package."*"]
debug = false
codegen-units = 256
opt-level = 's'

[profile.release]
debug = false
strip = true
codegen-units = 256
lto = true
opt-level = 's'
